version: '3.1'

services:
  db:
    container_name: "starevent-db"
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./dbinit/:/docker-entrypoint-initdb.d/
  monitoring:
    container_name: "starevent-monitoring"
    image: "prom/prometheus:v2.21.0"
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
