---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    project: mysql-test
type: Opaque
stringData:
  rootpassword: password
  eventdbpassword: eventdb
  reservationdbpassword: reservationdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  labels:
    project: mysql-test
data:
  init.sql: |
    CREATE DATABASE eventdb;
    CREATE USER 'eventdb' IDENTIFIED BY 'eventdb';
    GRANT ALL PRIVILEGES ON eventdb.* TO 'eventdb';
    FLUSH PRIVILEGES;
    USE eventdb;
    DROP TABLE IF EXISTS `event`;
    CREATE TABLE `event` (
      `id` bigint NOT NULL AUTO_INCREMENT,
      `title` varchar(200) NOT NULL,
      `artist` varchar(100) DEFAULT NULL,
      `description` varchar(500) DEFAULT NULL,
      `start_date` datetime DEFAULT NULL,
      `location` varchar(200) DEFAULT NULL,
      `address` varchar(200) DEFAULT NULL,
      `price` float NOT NULL,
      `availability` int NOT NULL,
      `img` varchar(500) DEFAULT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

    CREATE DATABASE reservationdb;
    CREATE USER 'reservationdb' IDENTIFIED BY 'reservationdb';
    GRANT ALL PRIVILEGES ON reservationdb.* TO 'reservationdb';
    FLUSH PRIVILEGES;
    USE reservationdb;
    DROP TABLE IF EXISTS `reservation`;
    CREATE TABLE `reservation` (
      `id` bigint NOT NULL AUTO_INCREMENT,
      `event_id` bigint NOT NULL,
      `user_id` varchar(100) NOT NULL,
      `secure_code` varchar(20) NOT NULL,
      `date` datetime NOT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    
    USE eventdb;
    INSERT INTO `event` ( `title`, `artist`, `description`, `start_date`, `location`, `address`, `price`, `availability`, `img`) VALUES
    ('Foo Fighters',	'Foo Fighters',	'Riconfermati i Foo Fghters nell ambito di I-Days Milano 2021. Scopri i dettagli!',	'2021-06-12 17:00:00',	'Milano',	'I-DAYS',	74.50,	1000,	'img/ff.jpg'),
    ('Deep Purple',	'Deep Purple THE WHOOSH! TOUR',	'Deep Purple THE WHOOSH! TOUR',	'2021-07-06 21:00:00',	'w2',	'a2',	57.50,	1000,	'img/dp.jpg'),
    ('James Blunt Once upon a tour',	'James Blunt',	'James Blunt ONCE UPON A MIND TOUR',	'2021-06-27 21:15:00',	'Milano',	'Mediolanum forum',	80.50,	700,	'img/jb.jpg'),
    ('Vasco Non stop live festival',	'Vasco Rossi',	'Vasco Non stop live festival',	'2021-06-27 21:15:00',	'Firenze',	'Visarno Arena',	80.50,	700,	'img/vr.jpg'),
    ('Hans Zimmer',	'Hans Zimmer',	'd2',	'2022-03-30 19:42:22',	'ASSAGO',	'Mediolanum Forum',	103.50,	1000,	'img/hz.jpg'),
    ('Carmen Consoli - Tour 2021',	'Carmen Consoli',	'Carmen Consoli torna con un nuovo tour nel 2021! Acquista subito il tuo biglietto!',	'2021-12-26 21:00:00',	'Roma',	'Auditorium Parco della Musica - Sala Santa Cecilia',	46,	1000,	'img/cc.jpg');