---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-configmap
  labels:
    project: starevent
data:
  prometheus.yml: |
    global:
      scrape_interval:     10s
    scrape_configs:
      - job_name: 'starevent-pods'
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            action: replace
            target_label: app_kubernetes_io_name
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_version]
            action: replace
            target_label: app_kubernetes_io_version
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
    project: starevent
spec:
  ports:
  - name: http
    port: 9090
    targetPort: 9090
  selector:
    app: prometheus
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
    project: starevent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
        project: starevent
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.21.0
        ports:
        - containerPort: 9090
        volumeMounts:
        #volume mount for prometheus config
          - name: prom-config
            mountPath: "/etc/prometheus"
            readOnly: true
      volumes:
        - name: prom-config
          configMap:
            name: prom-configmap
            items:
              - key: "prometheus.yml"
                path: "prometheus.yml"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configmap
  labels:
    project: starevent
data:
  datasource.yaml: |
    apiVersion: 1
    deleteDatasources:
      - name: Prometheus
        orgId: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus:9090
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
    project: starevent
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: grafana
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
    project: starevent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
        project: starevent
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - containerPort: 3000
        volumeMounts:
        #volume mount for grafana config
          - name: grafana-configmap
            mountPath: "/etc/grafana/provisioning/datasources"
            readOnly: true
      volumes:
        - name: grafana-configmap
          configMap:
            name: grafana-configmap
            items:
              - key: "datasource.yaml"
                path: "datasource.yaml"